name: (📡) Publish Release

on:
   release:
      types: [published]

jobs:
  publish-release:
    uses: sitepark/github-project-workflow/.github/workflows/maven-publish-release.yml@main
    secrets:
      MVN_REPO_SERVER_USERNAME: ${{ secrets.MVN_REPO_SERVER_USERNAME }}
      MVN_REPO_SERVER_PASSWORD: ${{ secrets.MVN_REPO_SERVER_PASSWORD }}
      MVN_REPO_SERVER_ID: ${{ secrets.MVN_REPO_SERVER_ID }}
      MVN_REPO_SERVER_SNAPSHOT_URL: ${{ secrets.MVN_REPO_SERVER_SNAPSHOT_URL }}

